---
- hosts: "{{ hosts }}"
  remote_user: "{{ username }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  tasks:
      - name: Installation d'ansible
        homebrew: name=ansible
      - name: Installation de python
        homebrew: name=python
      - name: Installation de wget
        homebrew: name=wget
      - name: Installation de imagemagick
        homebrew: name=imagemagick
      - name: Installation de htop
        homebrew: name=htop
      - name: Installation de dnsmasq
        homebrew: name=dnsmasq
      - name: Installation de cloc
        homebrew: name=cloc
      - name: Installation de awscli
        homebrew: name=awscli
      - name: Installation de node
        homebrew: name=node
      - name: Installation de nodejs
        homebrew: name=nodejs
      - name: Installation de npm
        homebrew: name=npm
      - name: Installation de nvm
        homebrew: name=nvm
      - name: Installation de cmatrix
        homebrew: name=cmatrix
      - name: Installation de pip
        easy_install: name=pip
      - name: Installation de mitproxy
        easy_install: name=mitproxy
      - name: Installation de httpie
        easy_install: name=httpie
      - name: Installation de composer
        get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer
